[colors]
cursor = { cursor = "#5c5855", text = "#f7f7f7" }
selection = { background = "#4a4543", text = "#f7f7f7" }

[colors.primary]
foreground = "#a5a2a2"
background = "#090300"

[colors.normal]
black = "#090300"
red = "#db2d20"
green = "#01a252"
yellow = "#fded02"
blue = "#01a0e4"
magenta = "#a16a94"
cyan = "#b5e4f4"
white = "#a5a2a2"

[colors.bright]
black = "#5c5855"
red = "#e8bbd0"
green = "#3a3432"
yellow = "#4a4543"
blue = "#807d7c"
magenta = "#d6d5d4"
cyan = "#cdab53"
white = "#f7f7f7"
